// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-veilshield-verifiers.mjs from Barretenberg Solidity verifier output.
// Do not edit by hand; regenerate after changing Noir circuits or bb versions.
pragma solidity ^0.8.27;

import {BaseZKHonkVerifier, Honk} from "./BaseZKHonkVerifier.sol";

uint256 constant TRANSFER_N = 32768;
uint256 constant TRANSFER_LOG_N = 15;
uint256 constant TRANSFER_NUMBER_OF_PUBLIC_INPUTS = 15;
uint256 constant TRANSFER_VK_HASH = 0x0cc0f9341dde753fa51b68f7c06b70d5288c822a84a3b5d576f82f8cc835a740;

library TransferVerificationKey {
    function loadVerificationKey() internal pure returns (Honk.VerificationKey memory) {
        Honk.VerificationKey memory vk = Honk.VerificationKey({
            circuitSize: uint256(32768),
            logCircuitSize: uint256(15),
            publicInputsSize: uint256(15),
            ql: Honk.G1Point({
               x: uint256(0x1761c7d223096efa5391851e80ae8cbd6c5a189a907cbbe0dc1a99b78d3f5477),
               y: uint256(0x2e3fd081cd75698c5b771a73e45f8f82e732d24485dafa0d0d558962c15a73c9)
            }),
            qr: Honk.G1Point({
               x: uint256(0x254422fbe7a0831770180c9652c21389cb699d39ad5a4981062a91f8e73bdfc9),
               y: uint256(0x08e62b29ccc82fe3ce3343cec8c83b6fc760332b174203024695df1cd26cd8e8)
            }),
            qo: Honk.G1Point({
               x: uint256(0x0a7446893a90ec01f69732638cedb94c78e82a8d2b37cdbe0df9c60a30b3bec8),
               y: uint256(0x0a1e063522a5e3dd6b0074bd333e93ec67cf117703262d37a9584489f47a9caf)
            }),
            q4: Honk.G1Point({
               x: uint256(0x0270e8d2d196e6c75bfe36b12222781c3ef2b4fc86700109537bcd0480c6dc51),
               y: uint256(0x0673665605edc1cc7f0a1754398cd1adb0a05a3f3a70ca98095458e9096f61d1)
            }),
            qm: Honk.G1Point({
               x: uint256(0x24a0e234ac67d5753aa1286a753e1cd1489d2ddb2783be7dc971ba5d0f95969a),
               y: uint256(0x28aebd7afc23cd5281e2f6cd9685b9bd0044502698799ea5b7c184137af77bbb)
            }),
            qc: Honk.G1Point({
               x: uint256(0x160480fc8b8fbed6632829472f9eb699a2194dd86ed65681fc0b4349e8f7edb9),
               y: uint256(0x0aac75d17759bd3cc383ec001bd09f484d8b8a5defa0249a4d7513e82bb96f00)
            }),
            qLookup: Honk.G1Point({
               x: uint256(0x0a68fcaf1183d6e5a9f7b697a04115e6f4a1753f9c2ddda9730a5fa5f1a1f8b9),
               y: uint256(0x1398a66eb6619b98eec08cd247293c7352bb56fda157b810bb5b8d624a6a6a31)
            }),
            qArith: Honk.G1Point({
               x: uint256(0x1c3bf2d60e07032b97716c11fe8029823444aa067a7545dc79b4136c2ff5a940),
               y: uint256(0x0c31c2ebfb7b9fe8648b597ed5d896baf28e0388fa8e3c87aee4b51c2bbc761f)
            }),
            qDeltaRange: Honk.G1Point({
               x: uint256(0x2f83ed1bd03784caf6c6f617acbca23d538ac6a9378251f5dfc3f337ec23ad63),
               y: uint256(0x07ccea3d843be1056dad2fe5d63d76527d759f28a358c61469037a51cd039230)
            }),
            qElliptic: Honk.G1Point({
               x: uint256(0x1aedf9519772fe3c111ac3300180b35a411e0a33f91b29666ec4923e8cf9c006),
               y: uint256(0x00742055e0181d6e105b4384eb9c91ce739fb94e4c9ecb2dc332cd1e93cabc10)
            }),
            qMemory: Honk.G1Point({
               x: uint256(0x170b8b21505fc216158b1c57dbc21b5607bb32223654aa467166c593403be6b3),
               y: uint256(0x227ba3bb07bdd073b5c78a1bc8e1111df51a0ecd830b4db0d475080773482de6)
            }),
            qNnf: Honk.G1Point({
               x: uint256(0x160301a03171c2c6e2e2b355413064fd0c122ed8f60693e0fe30dd94d5510040),
               y: uint256(0x0f87e7c979fd152b4133e8724e36e16c4ab530c4fc554673391437ddfeebb75a)
            }),
            qPoseidon2External: Honk.G1Point({
               x: uint256(0x034071a0789f2a11bc0fb71e9fc2a5b21098bf09e8797c19b33abdbcc1837b29),
               y: uint256(0x11e1614129e706329f691920184c17bc47cba17a1a26da183a9e3f14225d506e)
            }),
            qPoseidon2Internal: Honk.G1Point({
               x: uint256(0x1fcb3d5f29a02663c2da60ea1344acafc5e2c22df57d5caca1ad3851bd7e197f),
               y: uint256(0x1460978f13f46a6bdf488e1daf0733d11d034a1492e842b8658ec9740770e685)
            }),
            s1: Honk.G1Point({
               x: uint256(0x27eee2f5acd734c8cb56151040d7b86b9c163432258b9a6a2044225ea785eae7),
               y: uint256(0x2cc831fc2feafb81eff9b5e9fde171a83d6b7b17c0f7fecbf39c2cc9fc9607d0)
            }),
            s2: Honk.G1Point({
               x: uint256(0x032c78cc56f5bbd64f34726a008a4e3f16e2d9bf2796b91944b56deacc2176b6),
               y: uint256(0x242a99e4cbc222725f11313370482fc3eec88a76a8560a1bd0d146fe7330d71f)
            }),
            s3: Honk.G1Point({
               x: uint256(0x0f4b5b845b4821de0bd4af5309bd2892e75b37e98dc3373b87c688935d73a1a6),
               y: uint256(0x0d8ff0d453b62cf741f0db8e05662e2cc5bb601af9c5324143e4cdc1e959a68e)
            }),
            s4: Honk.G1Point({
               x: uint256(0x1c73e80b13c50aa29d5130d17695bee3124735e5b480609048dd62186a4ef72c),
               y: uint256(0x24b1c0327b2c3ba8971e2c6f39e713be2370b813ee39b239b0e7c7b66ab37024)
            }),
            t1: Honk.G1Point({
               x: uint256(0x12d7704cfeca3b972753ee50fabbe7a6f57cfd02f5f93fcf05366784d91cc60d),
               y: uint256(0x0a4d86d5f224165aeaa81ef90e8fa1d50ff9cd182b4f4ed5a9f59be7fe9a9346)
            }),
            t2: Honk.G1Point({
               x: uint256(0x0834b1bd3fdef02992a33f6bd7707f834a4a284272b1605df7818d8deeef70dc),
               y: uint256(0x2a25d7185ae0a620e4b69fca7f275b51ff9a930aca4211638d24a9652a2e6c1d)
            }),
            t3: Honk.G1Point({
               x: uint256(0x0f6038e156e30e8ad363ed61654bc34472c439684dace4b2f7461e6e961ec94d),
               y: uint256(0x16629b30e8a5d5508ecdfe69efd031a7ef7ecb005d326899cf31aaa204910d7c)
            }),
            t4: Honk.G1Point({
               x: uint256(0x2c77b4fac1b5cf7d931032e1a02e276637a26ccf2490226f565fd3eccc268758),
               y: uint256(0x2b72f1f101aca36669c67acf0c8a98607f09013ef1e670f084945a0e850b682c)
            }),
            id1: Honk.G1Point({
               x: uint256(0x176717877af1dbd79a1829dfa5deae44e746d256bf877b9402684b0f1be2994a),
               y: uint256(0x0654d0d4a9f68e708524cdd0b092d368d8b3b1b0e95c8ca4b41eebadac2eefe4)
            }),
            id2: Honk.G1Point({
               x: uint256(0x03045fe59b5afec460da546252f6aaa355ded9916bb5e439b6a64bf573d73000),
               y: uint256(0x024aff8ccec7f2b1608635da9c1b3ee39d6cb096c8ba780bc845f69d09b659dc)
            }),
            id3: Honk.G1Point({
               x: uint256(0x12b9e83c404b3c4a4a9d1bef76dc93afae64e1500fbbb206306f447553af64b0),
               y: uint256(0x014b955eb145073c2b89b75c37350ab952f8fddc8ee63dce291bf83a1c0e0443)
            }),
            id4: Honk.G1Point({
               x: uint256(0x181dbcc8c0f757b3a87571435aadbcde37ad76b041952cb295848954c63d39f7),
               y: uint256(0x2b7e162d8c66d8841b4010d53da6be1025f4bf7d70113d0b73ce7dcc623ce3d2)
            }),
            lagrangeFirst: Honk.G1Point({
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000001),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000002)
            }),
            lagrangeLast: Honk.G1Point({
               x: uint256(0x121215896876729215ee6072f5c4d0f6ffcea642f9e7902148bc9da17de27ee3),
               y: uint256(0x1789b5d8e83aadf9dc526e1047c41b3a97579ab24ac194eaa384403db62f6c8d)
            })
        });
        return vk;
    }
}

contract TransferVerifier is BaseZKHonkVerifier(TRANSFER_N, TRANSFER_LOG_N, TRANSFER_VK_HASH, TRANSFER_NUMBER_OF_PUBLIC_INPUTS) {
    function loadVerificationKey() internal pure override returns (Honk.VerificationKey memory) {
        return TransferVerificationKey.loadVerificationKey();
    }
}
