// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-veilshield-verifiers.mjs from Barretenberg Solidity verifier output.
// Do not edit by hand; regenerate after changing Noir circuits or bb versions.
pragma solidity ^0.8.27;

import {BaseZKHonkVerifier, Honk} from "./BaseZKHonkVerifier.sol";

uint256 constant WITHDRAW_N = 32768;
uint256 constant WITHDRAW_LOG_N = 15;
uint256 constant WITHDRAW_NUMBER_OF_PUBLIC_INPUTS = 13;
uint256 constant WITHDRAW_VK_HASH = 0x163814b857a1907f4545f3a5605e5b58229092aa27cee169bd6f9709302e6bb7;

library WithdrawVerificationKey {
    function loadVerificationKey() internal pure returns (Honk.VerificationKey memory) {
        Honk.VerificationKey memory vk = Honk.VerificationKey({
            circuitSize: uint256(32768),
            logCircuitSize: uint256(15),
            publicInputsSize: uint256(13),
            ql: Honk.G1Point({
               x: uint256(0x1e985ef2760afa6d11e025bdaa2837ef2d797f5cdbcabd6616a540b76dc67498),
               y: uint256(0x2056260e103b5c9b7ffeba23f59e69a3b8e5fd1982a01101cf6036a2e2561815)
            }),
            qr: Honk.G1Point({
               x: uint256(0x02c75deb0d850efa7db16504b54ace58fe1fdcfa2fdb3a183e5a0850971053d6),
               y: uint256(0x098768ec7f0d823c9efed0d7fa3ddc6e61991539d0ab19a6edc7c9230cab5d16)
            }),
            qo: Honk.G1Point({
               x: uint256(0x17b21a571a37eb82253da7398338b129d698d0417ec9909652c25163c4b991a6),
               y: uint256(0x1ff7e8f6436f12f01c5ee1c9848b94e776145e0b1e0d1870fd0dfd8885952476)
            }),
            q4: Honk.G1Point({
               x: uint256(0x221478157dc9fd1d710fa36af8bce9000733952014fe627302a6817ac748e1ba),
               y: uint256(0x28f4225c898eeac019040c1991c94d26b58ee784ed5fdec54875f1bfd09171af)
            }),
            qm: Honk.G1Point({
               x: uint256(0x016682a6e5670f842fad41afb98290b841448f6fe2ebdfc03ed79e09f3c3ecd2),
               y: uint256(0x18325d4a399254508c8770fe24a68a6b32610fb080424900a3ce677188aa4241)
            }),
            qc: Honk.G1Point({
               x: uint256(0x04fa2837ff73c67668c789abb73c5e30579b79a4798e04cb90d9dafc618cd960),
               y: uint256(0x212826619cbb2a320b72d28eddf9ea417a57f87a8a63e618b1de4bda118a9e6d)
            }),
            qLookup: Honk.G1Point({
               x: uint256(0x1013bc63b1bba6c57db7e85688cbf707f7c04aa30e153ae40092f7d42a0429a0),
               y: uint256(0x04bb9e0a2843c1341e29d0b46324d1a2d425237266054e3856ee3cf3e913f87e)
            }),
            qArith: Honk.G1Point({
               x: uint256(0x0694de9f47c86025c46f70a9681e01a10632177a908b8d8d248de12ff2567fc1),
               y: uint256(0x1e09f480a1faee565e78fcb985125c212541aa16c0e359c37a7d132ceff20552)
            }),
            qDeltaRange: Honk.G1Point({
               x: uint256(0x131ef4b5cb3ef9229a641a1e67039bd2aaea034cc743fabcc990ba6803db3a94),
               y: uint256(0x1efcfeb57d3c0b556227a10789a15755293fef2545a73d186506f2bce1fd5013)
            }),
            qElliptic: Honk.G1Point({
               x: uint256(0x2c5d5b6cfb19238c6eddfffdd6d7486cbc36b4d66bbef05824bec16394e6b2b2),
               y: uint256(0x1b66a8dbb1cea521c53a7384a6b25ece859b3c7b62e2d440e77b218efca9b681)
            }),
            qMemory: Honk.G1Point({
               x: uint256(0x137ee4abd49b4bf34fc57cb8f56e4a2c66af644b1ae8015efbca2ba816f2e5d6),
               y: uint256(0x1a43ae886ff0d178427fe7783d51ec9ec099bbda968fb68cab7c0b6266426114)
            }),
            qNnf: Honk.G1Point({
               x: uint256(0x0e363ebedba8efa9a16d97d5721a872eae3c0aecd5a3a7df8a07a5ad68bb54d0),
               y: uint256(0x12b88af37f93cd742b3ea24c97ee334e2defe7f8a060a4764a7d4e8b86bd5a1c)
            }),
            qPoseidon2External: Honk.G1Point({
               x: uint256(0x19a9bbb28b0995b8391f6ead195da78a9f845734d2938ba2211324cd5bf0ac1e),
               y: uint256(0x02c26a3c924f1a5d8fb1098a7191d2843d8d87aeabad861ca632c9a1383693d3)
            }),
            qPoseidon2Internal: Honk.G1Point({
               x: uint256(0x1aade0c482102c7e2862be1538b8cec05608815cdb4315cc1020ed6b79cfea6c),
               y: uint256(0x2604a9c1eef93731caa081ccdf60741498656e999548ee826674959803f90f7a)
            }),
            s1: Honk.G1Point({
               x: uint256(0x1ac4f57c15d3edbfb0e4526142c3add59a158272a76594ce511e771c3c7df63b),
               y: uint256(0x1b5d15648093b1c0bec1ff1bafd84fbd6439072eb465cfc10383380d8597e4b2)
            }),
            s2: Honk.G1Point({
               x: uint256(0x2c158f96a38617013e374deed292bf40343f894d5a7f08396fbf050d25c92eda),
               y: uint256(0x1b0d5c669e0ec200212a094d57be319a41d3221afbe50f30c6405a6247baf404)
            }),
            s3: Honk.G1Point({
               x: uint256(0x1d2f2b447f2b42f4e5e6c8c4466203bda205a0ee8f86231e4095d60137ab2f83),
               y: uint256(0x19b8d723c36e6504d7da205362c76058941214698efeee9c0ff99391be8f3563)
            }),
            s4: Honk.G1Point({
               x: uint256(0x2cd75f4ba9db801c163fe36ac45cfd0893a5c6ddf114a2769079eca80d0a5adc),
               y: uint256(0x13555b851019386ab0ed29c37a7382a6f108fce0df7e1131d76e3a997bf0ac1f)
            }),
            t1: Honk.G1Point({
               x: uint256(0x12d7704cfeca3b972753ee50fabbe7a6f57cfd02f5f93fcf05366784d91cc60d),
               y: uint256(0x0a4d86d5f224165aeaa81ef90e8fa1d50ff9cd182b4f4ed5a9f59be7fe9a9346)
            }),
            t2: Honk.G1Point({
               x: uint256(0x0834b1bd3fdef02992a33f6bd7707f834a4a284272b1605df7818d8deeef70dc),
               y: uint256(0x2a25d7185ae0a620e4b69fca7f275b51ff9a930aca4211638d24a9652a2e6c1d)
            }),
            t3: Honk.G1Point({
               x: uint256(0x0f6038e156e30e8ad363ed61654bc34472c439684dace4b2f7461e6e961ec94d),
               y: uint256(0x16629b30e8a5d5508ecdfe69efd031a7ef7ecb005d326899cf31aaa204910d7c)
            }),
            t4: Honk.G1Point({
               x: uint256(0x2c77b4fac1b5cf7d931032e1a02e276637a26ccf2490226f565fd3eccc268758),
               y: uint256(0x2b72f1f101aca36669c67acf0c8a98607f09013ef1e670f084945a0e850b682c)
            }),
            id1: Honk.G1Point({
               x: uint256(0x177299e76bb109f808a3cef06bd3523f582b49f4b58419652206b61d67301360),
               y: uint256(0x12d4adf3112a09d86d367293e029939c2a2b2e504aa08e1c4fee9b8980444013)
            }),
            id2: Honk.G1Point({
               x: uint256(0x2464a34728ed9268520c7b0e92fb302c2123dd3c3b8bdb8c4c38fe232e6e2f2b),
               y: uint256(0x295ca96a5c799d661a667d73633d628b8d66ba9ad8ea100dcbbe3d0697aafb5e)
            }),
            id3: Honk.G1Point({
               x: uint256(0x1c9ed84b72698eef04b3a92ed72f2dbc6e48d6395f7a32d3edbe5ddf6a950a5b),
               y: uint256(0x1f566cc0b59c89f4e55cb5ecf59f3ef7ef371066678babf7269018081057ac31)
            }),
            id4: Honk.G1Point({
               x: uint256(0x2f704c4ba5c8efff8334cf3ef42f7e9d72a5302f815951b7a86dba4823479182),
               y: uint256(0x0f7ec256515824bb91da78f3b7b7b718da2a32b9b5ce1294e4a32f1abc2edcd5)
            }),
            lagrangeFirst: Honk.G1Point({
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000001),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000002)
            }),
            lagrangeLast: Honk.G1Point({
               x: uint256(0x0e12c558f6ee4f14385691b8880d2e0fa90113074684d6fe640d7d2eebf0dca5),
               y: uint256(0x173e75c443f01725f88f223601a8ca16dc9d446c1c4e9a09c04cb2b6830d6818)
            })
        });
        return vk;
    }
}

contract WithdrawVerifier is BaseZKHonkVerifier(WITHDRAW_N, WITHDRAW_LOG_N, WITHDRAW_VK_HASH, WITHDRAW_NUMBER_OF_PUBLIC_INPUTS) {
    function loadVerificationKey() internal pure override returns (Honk.VerificationKey memory) {
        return WithdrawVerificationKey.loadVerificationKey();
    }
}
